checks:
  php:
    code_rating: true
    duplication: true

build:
  image: default-bionic
  environment:
    php: 8.1.12
  nodes:
    analysis:
      tests:
        override:
        - php-scrutinizer-run